(function($){$(document).ready(function(){$('body').removeClass('no-js').addClass('js');$('a#gototop').click(function(){$('html, body').animate({scrollTop:0},'slow');return false;});$('.hr').click(function(){$('html, body').animate({scrollTop:0},'slow');return false;});$('a.ttipw').tipsy({fade:true,gravity:'s',live:true});$('a.ttip').tipsy({fade:true,gravity:'w',live:true});var status=1;$('.widget.popular li').hover(function(){$(this).animate({opacity:0.8})
$(this).find('.comments-link').stop().animate({right:'0px'})},function(){$(this).find('.comments-link').stop().animate({right:'-10px'})
$(this).animate({opacity:1})})
$('.widget.popular h3 a').live("click",function(e){e.preventDefault();var el=$('#popular-container');var el_pop=$('#popular-container #popular-articles');var el_rec=$('#popular-container #recent-articles');var link=$('.widget.popular h3');var text1=$('#wi_po_text1').text();var text2=$('#wi_po_text2').text();if(el.hasClass('scrolled')){el.animate({left:'0px'},500).removeClass('scrolled');el_pop.animate({opacity:1})
el_rec.animate({opacity:0})
link.html('<h3>'+ text2+'<a class="ttip" href="#" title="'+ text1+'">'+ text1+'</a></h3>');}else{link.html('<h3>'+ text1+'<a class="ttip" href="#" title="'+ text2+'">'+ text2+'</a></h3>');el.animate({left:'-383px'},500).addClass('scrolled');el_pop.animate({opacity:0})
el_rec.animate({opacity:1})}
$(".tipsy").remove();})
$("select.mobile-nav").change(function(){window.location=$(this).find("option:selected").val();});$(".dropmenu li").hover(function(){$(this).has('ul').addClass("active");$(this).find('ul:first').css({visibility:"visible",display:"none"}).stop(true,true).slideDown('fast');},function(){$(this).removeClass("active");$(this).find('ul:first').css({visibility:"visible",display:"block"}).stop(true,true).slideUp('fast');});$("ul li:last-child").addClass("last-item")
$("ul li:first-child").addClass("first-item")
$($('.dropmenu li')).each(function(){if($(this).find('ul').size()>0){$(this).addClass("arrow");}});$("nav select").change(function(){window.location=$(this).find("option:selected").val();});$('table#wp-calendar tbody tr td').each(function(index,value){if($(this).children().length>0)$(this).addClass('post')});$('#sign-in').click(function(e){e.preventDefault();$("#signin-modal-box").modal({minWidth:340,minHeight:360,onOpen:function(dialog){dialog.overlay.fadeIn('normal',function(){dialog.data.hide();dialog.container.fadeIn('normal',function(){dialog.data.slideDown('normal');});});},onClose:function(dialog){dialog.data.fadeOut('normal',function(){dialog.container.hide('normal',function(){dialog.overlay.slideUp('fast',function(){$.modal.close();});});});}});})
$('#sign-up').click(function(e){e.preventDefault();$("#signup-modal-box").modal({minWidth:340,minHeight:340,onOpen:function(dialog){dialog.overlay.fadeIn('normal',function(){dialog.data.hide();dialog.container.fadeIn('normal',function(){dialog.data.slideDown('normal');});});},onClose:function(dialog){dialog.data.fadeOut('normal',function(){dialog.container.hide('normal',function(){dialog.overlay.slideUp('fast',function(){$.modal.close();});});});}});})
$('.share .share-post').live("click",function(e){e.preventDefault();$(this).parent().next(".share-modal-box").modal({minWidth:325,minHeight:240,onOpen:function(dialog){dialog.overlay.fadeIn('normal',function(){dialog.data.hide();dialog.container.fadeIn('normal',function(){dialog.data.slideDown('normal');});});},onClose:function(dialog){dialog.data.fadeOut('normal',function(){dialog.container.hide('normal',function(){dialog.overlay.slideUp('normal',function(){$.modal.close();});});});}});})
$('#featured .share-post').live("click",function(e){e.preventDefault();var id=$(this).attr('id');$('.share-modal-box.'+id).modal({minWidth:325,minHeight:240,onOpen:function(dialog){dialog.overlay.fadeIn('normal',function(){dialog.data.hide();dialog.container.fadeIn('normal',function(){dialog.data.slideDown('normal');});});},onClose:function(dialog){dialog.data.fadeOut('normal',function(){dialog.container.hide('normal',function(){dialog.overlay.slideUp('normal',function(){$.modal.close();});});});}});})
$(window).resize(onebyoneHandler);onebyoneHandler();function onebyoneHandler(){var elWidth=$('#articles').width(),elWidthF=parseInt(elWidth),elWidthH=Math.floor(elWidth/2);$('#featured .slides .oneByOne_item').css('width',elWidthF);$('#featured .slides .oneByOne_item img').css('max-width',elWidthH);$('#featured .slides div.slide-cont').css('width',elWidthH-40);$('.slides .share-post').css('left',elWidthH+20);}
$("a[class^='prettyPhoto']").prettyPhoto({deeplinking:false,theme:'dark_square'});$('.widget.magnovus-flickr ul li').hover(function(){$(this).find('a.zoom').stop().animate({right:'46px',opacity:1},'fast');$(this).find('a.link').stop().animate({right:'8px',opacity:1},'fast');},function(){$(this).find('a.zoom').stop().animate({right:'-40px',opacity:0},'fast');$(this).find('a.link').stop().animate({right:'-40px',opacity:0},'fast');})
$('.tabs-content .tab:first').show();$('.tabs li:first').addClass('active');$.each($('.tabs li'),function(i,el){$(el).click(function(){$('.tabs-content .tab').slideUp();$('.tabs-content .tab').eq(i).slideDown();$('.tabs li').removeClass('active');$(this).addClass('active');return false;});});$("div.accordion div:not(:first)").hide();$("div.accordion h4:first").addClass('active');$("div.accordion h4").click(function(){if($(this).next().is(":hidden")){$("div.accordion h4").removeClass('active');$("div.accordion div:visible").slideUp();$(this).next().slideDown();$(this).addClass('active');}
return false;});$(".toggle-container").hide();$(".toggle-trigger").click(function(){$(this).toggleClass("active").next().slideToggle();return false;});$(".box-close").click(function(e){e.preventDefault();$(this).parent().parent().fadeOut();})
$('.ratingblock').hover(function(){$(this).find(".ratingtext").css('opacity',0).animate({'opacity':1},500);},function(){$(this).find(".ratingtext").css('opacity',1).animate({'opacity':0},500);});$('.flexslider').flexslider({controlNav:false,directionNav:true});$('.gallery-item').hover(function(){$(this).find(".wp-caption-text").animate({'opacity':0,'bottom':'-100px'},500);},function(){$(this).find(".wp-caption-text").animate({'opacity':1,'bottom':'0px'},500);});$('.posts-column .thumb-container').hover(function(){$(this).find('.comments-link').addClass('animated bounce');},function(){$(this).find('.comments-link').removeClass('animated bounce');})});$.fn.setAllToMaxHeight=function(){return this.height(Math.max.apply(this,$.map(this,function(e){return $(e).height()})));}
$.fn.imagesLoaded=function(callback){var elems=this.find('img'),len=elems.length,_this=this;elems.bind('load',function(){if(--len<=0){callback.call(_this);}}).each(function(){if(this.complete||this.complete===undefined){var src=this.src;this.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";this.src=src;}});return this;};})(this.jQuery);